
THORSANVIL_ROOT				?= $(realpath ../../)

TARGET						= ThorsLogging.lib
NAMESPACE					= ThorsAnvil::Logging
CXXFLAGS					+= -DLOGURU_WITH_STREAMS=1

include $(THORSANVIL_ROOT)/build/tools/Makefile

